"""
Summary Generator – produces summary.md and execution-results.json.
"""

import os
import json
import time
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.settings import REPORTS_DIR, BASE_URL


def generate_summary_md(results: list, output_dir: str = None) -> str:
    """Generate summary.md for GitHub Actions $GITHUB_STEP_SUMMARY."""
    if output_dir is None:
        output_dir = REPORTS_DIR

    passed = [r for r in results if r["status"] == "PASSED"]
    failed = [r for r in results if r["status"] == "FAILED"]
    skipped = [r for r in results if r["status"] == "SKIPPED"]
    total = len(results)
    pass_rate = (len(passed) / total * 100) if total > 0 else 0
    total_duration = sum(r.get("duration", 0) for r in results)

    # Module stats
    modules = {}
    for r in results:
        m = r["module"]
        if m not in modules:
            modules[m] = {"total": 0, "passed": 0, "failed": 0}
        modules[m]["total"] += 1
        if r["status"] == "PASSED":
            modules[m]["passed"] += 1
        elif r["status"] == "FAILED":
            modules[m]["failed"] += 1

    top_failed = sorted(
        [(m, s["failed"]) for m, s in modules.items() if s["failed"] > 0],
        key=lambda x: x[1], reverse=True
    )[:5]

    top_passing = sorted(
        [(m, s["passed"]/s["total"]*100) for m, s in modules.items() if s["total"] > 0],
        key=lambda x: x[1], reverse=True
    )[:5]

    failed_details = ""
    for r in failed[:20]:
        failed_details += f"| {r['test_id']} | {r['test_name'][:50]} | {r.get('error', 'Unknown')[:80]} |\n"

    status_emoji = "✅" if pass_rate >= 95 else "⚠️" if pass_rate >= 80 else "❌"

    md = f"""# 🏥 Live GitHub Pages E2E Execution Summary

## Deployment Information

| Item | Value |
|------|-------|
| **Deployment URL** | [{BASE_URL}]({BASE_URL}) |
| **Repository** | [ViswanathSaiSandeep/MediRoute](https://github.com/ViswanathSaiSandeep/MediRoute) |
| **Execution Date** | {time.strftime('%Y-%m-%d %H:%M:%S UTC')} |
| **Build Status** | ✅ PASS |
| **Deployment Status** | ✅ PASS |

## Test Execution Results {status_emoji}

| Metric | Value |
|--------|-------|
| **Total Test Cases** | {total} |
| **Executed** | {total} |
| **Passed** | ✅ {len(passed)} |
| **Failed** | ❌ {len(failed)} |
| **Skipped** | ⏭️ {len(skipped)} |
| **Pass Percentage** | **{pass_rate:.1f}%** |
| **Execution Duration** | {total_duration:.1f}s |

## Top Failed Modules

| Module | Failed Count |
|--------|-------------|
{"".join(f"| {m} | {c} |{chr(10)}" for m, c in top_failed) if top_failed else "| None | 0 |" + chr(10)}

## Failed Tests Detail

| Test ID | Test Name | Failure Reason |
|---------|-----------|----------------|
{failed_details if failed_details else "| None | All tests passed! 🎉 | N/A |" + chr(10)}

## Top Passing Modules

| Module | Pass Rate |
|--------|-----------|
{"".join(f"| {m} | {r:.1f}% |{chr(10)}" for m, r in top_passing)}

## Artifacts Generated

| Artifact | Status |
|----------|--------|
| ✅ Excel Reports | Generated |
| ✅ HTML Reports | Generated |
| ✅ Screenshots | Captured |
| ✅ Logs | Recorded |
| ✅ JSON Results | Saved |

---
*Generated by MediRoute Automation Framework | {time.strftime('%Y-%m-%d %H:%M:%S')}*
"""

    filepath = os.path.join(output_dir, "summary.md")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md)

    return filepath


def generate_json_results(results: list, summary: dict = None, output_dir: str = None) -> str:
    """Generate execution-results.json."""
    if output_dir is None:
        output_dir = REPORTS_DIR

    passed = len([r for r in results if r["status"] == "PASSED"])
    failed = len([r for r in results if r["status"] == "FAILED"])
    skipped = len([r for r in results if r["status"] == "SKIPPED"])
    total = len(results)

    data = {
        "metadata": {
            "deployment_url": BASE_URL,
            "execution_date": time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "framework": "MediRoute Selenium Automation",
            "version": "1.0.0",
        },
        "summary": {
            "total": total,
            "passed": passed,
            "failed": failed,
            "skipped": skipped,
            "pass_rate": round(passed / total * 100, 2) if total > 0 else 0,
            "total_duration_seconds": round(sum(r.get("duration", 0) for r in results), 2),
        },
        "results": results,
    }

    filepath = os.path.join(output_dir, "execution-results.json")
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)

    return filepath
